//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmplyeeName { get; set; }
        public string EmplyeePosition { get; set; }
        public Nullable<double> EmplyeeSalary { get; set; }
        public string EmplyeeOffice { get; set; }
        public string EmployeeImage { get; set; }

        [NotMapped]
        public HttpPostedFileBase imageFile { get; set; }

        public Employee()
        {
            EmployeeImage = "~/Documents/Images/default.png";
        }
    }
}
